### ISSUE TITLE
Consider using `spsmInitialize` just above `spsmShutdown`

### ISSUE THREAD

**Issue by lucasaf04** [eradicatinglove/Quick-Reboot#1]
As it is now, the spsm service remains created if the user chooses to go back to the homebrew menu.
Example from another well known project: https://github.com/exelix11/SwitchThemeInjector/blob/e12a959e050292e8bfa40c72017bb0cad8d61fbe/SwitchThemesNX/source/Platform/PlatformSwitch.cpp#L114-L115

Thanks for the app!!

**Comment by eradicatinglove** [comment]
Hey sorry took long to reply. busy work schedules. anyway. i appreciate your feedback. i have changed the script in main.cpp to what you mentioned. now spsmInitialize() is right above spsmShutdown(true). i had so many different things i was writing at the time and finally saw how spsm was the better option than what the mess i was looking into. thanks for the kind words.
